name: CI/CD

on:
  push:
    branches:
      - main

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - name: Получить код
      uses: actions/checkout@v4

    - name: Установить .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Восстановить зависимости
      run: dotnet restore

    - name: Собрать проект
      run: dotnet build --no-restore

    - name: Запустить тесты
      run: dotnet test --no-build
